server:
  port: 8081

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo
    username: xxx
    password: xxx
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
